apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tippspiel.fullname" . }}-keycloak
  labels:
    {{- include "tippspiel.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.adminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | quote }}
