apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tippspiel.fullname" . }}-app
  labels:
    {{- include "tippspiel.labels" . | nindent 4 }}
type: Opaque
stringData:
  # DB credentials shared by both services (same PG instance, different DBs)
  DB_USER:     {{ .Values.postgres.credentials.user | quote }}
  DB_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
